### ISSUE TITLE
[Request] for a license

### ISSUE THREAD

**Issue by pwuethri** [sungsoo-ahn/genetic-expert-guided-learning#1]
Hello @sungsoo-ahn,

Thank you very much for making the GEGL source code available to the community, it is really clean and works like a charm! :)

Could you please add a license to this repository? [https://choosealicense.com](https://choosealicense.com/) is a great starting point in figuring out the different types of available licenses.

Thank you very much in advance!

Pierre

**Comment by sungsoo-ahn** [comment]
Hi, Thanks for the generous feedback! I added the MIT license to our repository.

**Comment by pwuethri** [comment]
Thank you very much for your quick response and action, I truly appreciate it! 

Closing this issue since it has been resolved.
